joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 2.0
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

